baseurl = "https://julian7.github.io/"
languageCode = "en-us"
title = "Operation 500-pound Parakeet"
canonifyurls = true
paginate = 10
theme = "startbootstrap-clean-blog"
disqusShortname = "op500lbs"
copyright = "All articless written by Balazs Nagy. I might not share the viewpoints of my employer."

[author]
name = 'Balazs Nagy'

[params]
DateForm = "Mon, Jan 2, 2006"
Description = "Jul's blog"
Author = "Balazs Nagy"
email = "julsevern@gmail.com"
Ganalytics = "UA-9690247-6"

[[params.social]]
title = "twitter"
url = "https://twitter.com/julsevern"

[[params.social]]
title = "github"
url = "https://github.com/julian7"

[[menu.main]]
name = "home"
url = "/"
weight = -200
